### ISSUE TITLE
[Question] Support period

### ISSUE THREAD

**Issue by FaySmash** [ChonDoit/treble_colt_patches#1]
Hey just a quick question if I can choose your build as my daily driver. Are you planing publish new Android 13 builds now and then? The ROM runs amazing on my device, thanks for your efforts!

**Comment by ChonDoit** [comment]
> Hey just a quick question if I can choose your build as my daily driver. Are you planing publish new Android 13 builds now and then? The ROM runs amazing on my device, thanks for your efforts!

A13 source is EOL. As much i will push an update to fix a random jitter/lag on UI, but first must figure out source of the issue

**Comment by FaySmash** [comment]
> A13 source is EOL. As much i will push an update to fix a random jitter/lag on UI, but first must figure out source of the issue

Thanks for the fast reply! Looking forward for the fix then. If the source is EOL, there won't be any new A13 GSIs I suppose, so I might as well stick with this ROM.

**Comment by dp-28AKM** [comment]
Call recorder not working fix this and can you make display more saturated like 1.5x please i am color blind my eyes like saturated Color please
